apiVersion: batch/v1
kind: Job
metadata:
  name: spark-job
spec:
  template:
    metadata:
      labels:
        app: spark-driver
    spec:
      restartPolicy: OnFailure
      containers:
      - name: spark-driver-container
        image: 290071265645.dkr.ecr.eu-west-3.amazonaws.com/data-pipeline:latest
        workingDir: /opt/spark/work-dir
        volumeMounts:
        - mountPath: "/opt/spark/work-dir/src"
          name: my-volume
        command:
        - "/opt/spark/bin/spark-submit"
        args:
        - "--class"
        - "Main"
        - "local:///opt/spark/work-dir/dataprocessing-assembly-0.1.0-SNAPSHOT.jar"
        - "-i"
        - "src/data/0308.csv"
        - "-o"
        - "src/data/output/"
      volumes:
      - name: my-volume
        persistentVolumeClaim:
         claimName: my-efs-pvc
